<?php

/**
* Implements hook_install()
*
* Change the weight of the module.
* This module's hook implementations will be the last to run, we need them to run after
* workbench moderation's implemntations
*/
function ef_workbench_moderation_state_access_install() {
 db_update('system')
   ->fields(array('weight' => 1000))
   ->condition('name', 'ef_workbench_moderation_state_access', '=')
   ->execute();
}
