<?php
/**
 * @file
 * ef_taxonomy_permissions.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function ef_taxonomy_permissions_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'add terms in ef_case_study_categories'.
  $permissions['add terms in ef_case_study_categories'] = array(
    'name' => 'add terms in ef_case_study_categories',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_initiative_types'.
  $permissions['add terms in ef_case_study_initiative_types'] = array(
    'name' => 'add terms in ef_case_study_initiative_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_legal_forms'.
  $permissions['add terms in ef_case_study_legal_forms'] = array(
    'name' => 'add terms in ef_case_study_legal_forms',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_names'.
  $permissions['add terms in ef_case_study_names'] = array(
    'name' => 'add terms in ef_case_study_names',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_organisation_sizes'.
  $permissions['add terms in ef_case_study_organisation_sizes'] = array(
    'name' => 'add terms in ef_case_study_organisation_sizes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_scopes'.
  $permissions['add terms in ef_case_study_scopes'] = array(
    'name' => 'add terms in ef_case_study_scopes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_sectors'.
  $permissions['add terms in ef_case_study_sectors'] = array(
    'name' => 'add terms in ef_case_study_sectors',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_social_dialogue_types'.
  $permissions['add terms in ef_case_study_social_dialogue_types'] = array(
    'name' => 'add terms in ef_case_study_social_dialogue_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_social_dialogues'.
  $permissions['add terms in ef_case_study_social_dialogues'] = array(
    'name' => 'add terms in ef_case_study_social_dialogues',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_case_study_target_groups'.
  $permissions['add terms in ef_case_study_target_groups'] = array(
    'name' => 'add terms in ef_case_study_target_groups',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_company_sizes'.
  $permissions['add terms in ef_company_sizes'] = array(
    'name' => 'add terms in ef_company_sizes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_contracts'.
  $permissions['add terms in ef_contracts'] = array(
    'name' => 'add terms in ef_contracts',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_deliverable_kinds'.
  $permissions['add terms in ef_deliverable_kinds'] = array(
    'name' => 'add terms in ef_deliverable_kinds',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_event_types'.
  $permissions['add terms in ef_event_types'] = array(
    'name' => 'add terms in ef_event_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_industrial_relations_terms'.
  $permissions['add terms in ef_industrial_relations_terms'] = array(
    'name' => 'add terms in ef_industrial_relations_terms',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_instrument_categories'.
  $permissions['add terms in ef_instrument_categories'] = array(
    'name' => 'add terms in ef_instrument_categories',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_instrument_fundings'.
  $permissions['add terms in ef_instrument_fundings'] = array(
    'name' => 'add terms in ef_instrument_fundings',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_instrument_involvement_types'.
  $permissions['add terms in ef_instrument_involvement_types'] = array(
    'name' => 'add terms in ef_instrument_involvement_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_instrument_phases'.
  $permissions['add terms in ef_instrument_phases'] = array(
    'name' => 'add terms in ef_instrument_phases',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_nace_codes'.
  $permissions['add terms in ef_nace_codes'] = array(
    'name' => 'add terms in ef_nace_codes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_nuts'.
  $permissions['add terms in ef_nuts'] = array(
    'name' => 'add terms in ef_nuts',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_observatories'.
  $permissions['add terms in ef_observatories'] = array(
    'name' => 'add terms in ef_observatories',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_procurement_statuses'.
  $permissions['add terms in ef_procurement_statuses'] = array(
    'name' => 'add terms in ef_procurement_statuses',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_procurement_types'.
  $permissions['add terms in ef_procurement_types'] = array(
    'name' => 'add terms in ef_procurement_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_publication_contributors'.
  $permissions['add terms in ef_publication_contributors'] = array(
    'name' => 'add terms in ef_publication_contributors',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_publication_keywords'.
  $permissions['add terms in ef_publication_keywords'] = array(
    'name' => 'add terms in ef_publication_keywords',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_publication_sectors'.
  $permissions['add terms in ef_publication_sectors'] = array(
    'name' => 'add terms in ef_publication_sectors',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_publication_types'.
  $permissions['add terms in ef_publication_types'] = array(
    'name' => 'add terms in ef_publication_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_regulation_fundings'.
  $permissions['add terms in ef_regulation_fundings'] = array(
    'name' => 'add terms in ef_regulation_fundings',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_regulation_involvements'.
  $permissions['add terms in ef_regulation_involvements'] = array(
    'name' => 'add terms in ef_regulation_involvements',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_regulation_phases'.
  $permissions['add terms in ef_regulation_phases'] = array(
    'name' => 'add terms in ef_regulation_phases',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_regulation_thresholds'.
  $permissions['add terms in ef_regulation_thresholds'] = array(
    'name' => 'add terms in ef_regulation_thresholds',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_regulation_types'.
  $permissions['add terms in ef_regulation_types'] = array(
    'name' => 'add terms in ef_regulation_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_report_types'.
  $permissions['add terms in ef_report_types'] = array(
    'name' => 'add terms in ef_report_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_restructuring_keywords'.
  $permissions['add terms in ef_restructuring_keywords'] = array(
    'name' => 'add terms in ef_restructuring_keywords',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_restructuring_types'.
  $permissions['add terms in ef_restructuring_types'] = array(
    'name' => 'add terms in ef_restructuring_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_sectors'.
  $permissions['add terms in ef_sectors'] = array(
    'name' => 'add terms in ef_sectors',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_spotlight_themes'.
  $permissions['add terms in ef_spotlight_themes'] = array(
    'name' => 'add terms in ef_spotlight_themes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_survey_families'.
  $permissions['add terms in ef_survey_families'] = array(
    'name' => 'add terms in ef_survey_families',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_themes'.
  $permissions['add terms in ef_themes'] = array(
    'name' => 'add terms in ef_themes',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_topics'.
  $permissions['add terms in ef_topics'] = array(
    'name' => 'add terms in ef_topics',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_units'.
  $permissions['add terms in ef_units'] = array(
    'name' => 'add terms in ef_units',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_vendor_service_types'.
  $permissions['add terms in ef_vendor_service_types'] = array(
    'name' => 'add terms in ef_vendor_service_types',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in ef_work_programme_areas'.
  $permissions['add terms in ef_work_programme_areas'] = array(
    'name' => 'add terms in ef_work_programme_areas',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in newsletter'.
  $permissions['add terms in newsletter'] = array(
    'name' => 'add terms in newsletter',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  // Exported permission: 'add terms in tags'.
  $permissions['add terms in tags'] = array(
    'name' => 'add terms in tags',
    'roles' => array(
      'Metadata Manager' => 'Metadata Manager',
      'administrator' => 'administrator',
    ),
    'module' => 'taxonomy_access_fix',
  );

  return $permissions;
}
