<?php

/**
 * @file
 * Integration of Cache Expiration module version 7.x-2.x and Authcache Builtin.
 */

/**
 * Implements hook_expire_cache().
 *
 * Expire cache support for the builtin cache handler.
 */
function authcache_builtin_expire_v2_expire_cache($urls, $wildcards, $object_type, $object) {

  $wildcard_urls = [];
  $non_wildcard_urls = [];
  foreach (array_keys($urls) as $path) {
    $url = url($path, ['absolute' => FALSE, 'alias' => TRUE]);
    if (empty($wildcards[$path])) {
      $wildcard_urls[] = $url;
    }
    else {
      $non_wildcard_urls[] = $url;
    }
  }

  $cids = array();
  $wildcard_cids = array();
  foreach (authcache_enum_keys() as $key) {
    foreach ($wildcard_urls as $url) {
      $wildcard_cids[] = $key . $url;
    }
    foreach ($non_wildcard_urls as $url) {
      $cids[] = $key . $url;
    }
  }

  if (!empty($cids)) {
    cache_clear_all($cids, 'cache_page');
  }

  foreach ($wildcard_cids as $cid) {
    cache_clear_all($cid, 'cache_page', TRUE);
  }
}
