<?php

/**
 * Implements hook_form_alter().
 */
function ef_show_contract_numbers_in_contract_fields_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  // user create and edit forms
  if (($form['#form_id'] == 'user_register_form' || $form['#form_id'] == 'user_profile_form')
    && isset($form['field_ef_contracts']) && $form['field_ef_contracts']['#access']) {
    show_contract_numbers_in_selects($form, 'field_ef_contracts');
  }

  if ($form_id == 'user_register_form' && in_array('OSU', $user->roles)) {
    $country_group_roles = array('Country Group Leader', 'Country Group Member',);
    $form['field_ef_notification_settings']['und']['#default_value'] = 1;
    $form['field_ef_notification_settings']['#type'] = 'hidden';
    $form['country'] = array(
      '#type' => 'fieldset',
      '#weight' => 5,
      '#title' => t('Country group settings'), 
      '#collapsible' => FALSE, 
      '#collapsed' => FALSE,
    );
    $form['country']['ef_country_group'] = array(
      '#type' => 'select',
      '#title' => t('Country Group'),
      '#options' => get_country_groups(),
    );

    $group_roles = group_type_load('country_group')->getRoles(FALSE);
    foreach ($group_roles as &$group_role) {
      $group_role = $group_role->label();
    }

    unset($group_roles['country_group_creator']);
    unset($group_roles['group_admin']);

    $form['country']['ef_country_group_roles'] = array(
      '#type' => 'radios',
      '#title' => t('Country Group role'),
      '#description' => t('Select a role for the user in the Country Group'),
      '#multiple' => FALSE,
      '#options' => $group_roles,
      '#default_value' => 'country_group_member',
    );

    $form['#submit'][] = 'osu_new_author_register_submit';
  }
}

function show_contract_numbers_in_selects(&$form, $field_name) {
  $contract_options = $form[$field_name][LANGUAGE_NONE]['#options']; // contract id -> contract title
  foreach ($contract_options as $contract_id => $contract_title) {
    if ($contract_id !== '_none') {
      $contract = taxonomy_get_term_by_name($contract_title, 'ef_contracts');
      $contract_number = $contract[$contract_id]->field_ef_contract_number['und'][0]['safe_value'];
      $contract_title_short = str_replace("Network of Correspondents - ", "", $contract_title);
      $contract_title_short = str_replace("Provision of ", "", $contract_title_short);
      $contract_options_with_number[$contract_id] = $contract_number . ': ' . $contract_title_short;
    }
  }
  $form[$field_name][LANGUAGE_NONE]['#options'] = $contract_options_with_number;
}

function osu_new_author_register_submit($form, &$form_state) {
  global $user;

  if ($form_state['values']['ef_country_group_roles'] == 'country_group_member') {
    $role = array(
      'country_group_member' => 'country_group_member',
      'country_group_leader' => 0,
    );
  }
  else {
    $role = array(
      'country_group_leader' => 'country_group_leader',
      'country_group_member' => 0,
    );
  }

  $values = array(
    'roles' => array_filter($role),
    'added_on' => REQUEST_TIME,
    'added_by' => $user->uid,
  );

  if (isset($form_state['values']['uid']) && isset($form_state['values']['ef_country_group'])) {
    $group = group_load(intval($form_state['values']['ef_country_group']));
    $group->addMember($form_state['values']['uid'], $values);
  }
}