<?php

function ef_ckeditor_colorbutton_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      return array(
        'colorbutton' => array( // Internal plugin name
          'extensions' => array(
            'colorbutton' => t('Color Button'), // Internal plugin name as key, name visible in editor profile config UI as value.
          ),
          'load' => TRUE,
          'internal' => FALSE,
          'path' => 'sites/all/libraries/ckeditor/plugins/colorbutton'
        ),
      );
     break;
  }
}
