<?php

/*
* Implements hook_permission()
*/
function ef_topics_page_permission(){
  return array(
    'access_ef_topics_page' => array(
      'title' => t('Access to EF Topics page'),
      'description' => t('Allow access to contextual topics page'),
    ),
  );
}

/*
* Implements hook_menu()
*/
function ef_topics_page_menu(){

  $items['topic/%'] = array(
    'title' => '%',
    'page callback' => 'topics_page',
    'page arguments' => array(1),
    'access arguments' => array('access_ef_topics_page'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['topics_page/%/%'] = array(
    'page callback' => '_update_topics_tab',
    'page arguments' => array(2,3),
    'type' => MENU_CALLBACK, 
  );


   return $items;
}
/*
*  Form building function
*/
function topics_page($contextual_term = ''){
  
    // Call defined theme for ef_topics_page
  return theme('ef_topics_page',
      array(
        'contextual_term' => $contextual_term,
        'main_image' => NULL, 
        'summary' => NULL,
        'subscription' => NULL,
        'description' => NULL,
        'topics' => NULL,
        'tabs' => NULL,
        'featured_block' => NULL, 
        'related_links_block' => NULL,
        'ef_activities' => NULL,
      )
    );
}

/*
* Implements hook_theme()
*/
function ef_topics_page_theme(){
  return array(
    'ef_topics_page' => array(
      'template' => 'ef-topics-page',
      'variables' => array(
                      'contextual_term' => NULL,
                      'main_image' => NULL,
                      'summary' => NULL,
                      'subscription' => NULL,
                      'description' => NULL,
                      'topics' => NULL,
                      'tabs' => NULL,
                      'featured_block' => NULL,
                      'related_links_block' => NULL,
                      'ef_activities' => NULL,
                      'subscription_url' => NULL,
                    ),
      'file' => 'preprocessor.inc'
    ),
  );
}


/*
 * Implements HOOK_form_alter(&$form, &$form_state, $form_id)
 */
function ef_topics_page_form_alter(&$form, &$form_state, $form_id){

  if($form['#id'] == 'taxonomy-form-term')
  {
    
    // For checkboxes checked condition needs to be used
    $form['field_term_subscription_url']['#states'] = array(
      'visible' => array(
        'input[name="field_ef_subscription_msg[und]"]' => array('checked' => TRUE))
        );

    $form['field_term_key_topic']['#states'] = array(
      'visible' => array(
        'input[name="field_term_promote_to_home_page[und]"]' => array('checked' => TRUE))
        );
 
  }

}

function _update_topics_tab($content_type_name, $page){
  dpm($content_type_name);
  dpm($page);

}