<?php

require_once __DIR__ . '/ef_pleco_components.field_group.inc';
require_once __DIR__ . '/ef_pleco_components.ds.inc';

/**
 * Implements hook_cfrplugin_info().
 */
function ef_pleco_components_cfrplugin_info() {
  return cfrplugindiscovery()->moduleFileScanPsr4(__FILE__);
}

/**
 * Implements hook_theme().
 */
function ef_pleco_components_theme() {
  return [
    /* @see template_preprocess_ef_pleco_keyvaluetable() */
    'ef_pleco_keyvaluetable' => [
      'render element' => 'element',
      'file' => 'ef_pleco_components.theme.inc',
      'template' => 'ef-pleco-keyvaluetable',
    ],
    /* @see template_preprocess_ef_pleco_related_entity() */
    'ef_pleco_related_entity' => [
      'render element' => 'element',
      'file' => 'ef_pleco_components.theme.inc',
      'template' => 'ef-pleco-related-entity',
    ],
  ];
}
