<?php 

/**
 * Implementation of hook_node_insert().
 */

function ef_factsheet_id_node_presave($node){
	if(!isset($node->original)){
		   if($node->type=="ef_factsheet"){
				$value = db_query('SELECT max( cast(field_ef_migration_factsheet_key_value as unsigned)) 
					FROM field_data_field_ef_migration_factsheet_key')->fetchField();
				$node->field_ef_migration_factsheet_key['und'][0]['value'] = (string)($value + 1);
		   }
	}
}