#wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=del" 
#sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=1000&to=100" 
sleep 3
#wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=del" 
#sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=1000&to=100" 
sleep 3
#wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/national-basic-pages.php?action=del" 
#sleep 3
wget "http://eurofound.europa.eu/ef/sites/all/_docs/migration/national-basic-pages.php?action=migrate" 