wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/basic-pages.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=0&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=10&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=20&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=30&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=40&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=50&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=60&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=70&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=80&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=90&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=100&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=110&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=120&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=130&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=140&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=150&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=160&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=170&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=180&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=190&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=200&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=210&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=220&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=230&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=240&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=250&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=260&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-contribution.php?action=migrate&from=270&to=10" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=1000&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=1100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/case-studies.php?action=migrate&from=1200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=0&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=1900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=2900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=3900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=4900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=5900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=6900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=7900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=8900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=9900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=10900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=11900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=12900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=13900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ef-articles.php?action=migrate&from=14000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=0&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=1900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=2900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=3900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=4900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=5900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=6900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=7900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=8900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=9900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=10900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/emire.php?action=migrate&from=11000&to=100"
sleep 3
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/events.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=0&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=1900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=2900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=3900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=4900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=5900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=6900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=7900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=8900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=9900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=10900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=11900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=12900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=13900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=14900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=15900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=16900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=17900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18100&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18200&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18300&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18400&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18500&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18600&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18700&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18800&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=18900&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/factsheets.php?action=migrate&from=19000&to=100"
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ir-dictionary.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ir-dictionary.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ir-dictionary.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ir-dictionary.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/ir-dictionary.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=1000&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=1100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/news.php?action=migrate&from=1200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=del" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1000&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=1900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/publications.php?action=migrate&from=2000&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=0&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=100&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=200&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=300&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=400&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=500&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=600&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=700&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=800&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/survey-basic-pages.php?action=migrate&from=900&to=100" 
sleep 3
wget "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/national-basic-pages.php?action=migrate"
sleep 3
wget  "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/vacancies.php?action=migrate"
sleep 3
wget  "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/board.php?action=migrate"
sleep 3
wget  "http://efstaging2.eworx.gr/ef/sites/all/_docs/migration/call-for-tender.php?action=migrate"
sleep 3