<?php
/**
 * @file
 * ef_car_group_documents.field_group.inc
 */

/**
 * Implements hook_field_group_info().
 */
function ef_car_group_documents_field_group_info() {
  $export = array();

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_documents|node|ef_comparative_analytical_report|default';
  $field_group->group_name = 'group_documents';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'ef_comparative_analytical_report';
  $field_group->mode = 'default';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => '',
    'weight' => '17',
    'children' => array(
      0 => 'field_ef_document',
      1 => 'field_ef_documents',
      2 => 'field_ef_source_documents',
    ),
    'format_type' => 'fieldset',
    'format_settings' => array(
      'label' => '',
      'instance_settings' => array(
        'classes' => 'nc-attached-documents',
        'description' => '',
      ),
      'formatter' => 'open',
    ),
  );
  $export['group_documents|node|ef_comparative_analytical_report|default'] = $field_group;

  return $export;
}
