<?php

use Drupal\cfrplugin\Hub\CfrPluginHub;

require_once __DIR__ . '/cfrplugin.form_element.inc';
require_once __DIR__ . '/cfrplugin.menu.inc';

/**
 * @return \Drupal\cfrplugin\Hub\CfrPluginHubInterface
 */
function cfrplugin() {
  static $hub;
  return isset($hub)
    ? $hub
    : $hub = CfrPluginHub::create();
}

/**
 * Implements hook_permission().
 *
 * @return array[]
 */
function cfrplugin_permission() {
  return [
    'view cfrplugin report' =>  [
      'title' => t('View report of Cfr plugins'),
      'restrict access' => TRUE,
      'warning' => t('The report page might reveal some implementation details.'),
    ],
  ];
}

/**
 * Implements hook_admin_menu_cache_info()
 *
 * @return array[]
 */
function cfrplugin_admin_menu_cache_info() {

  $caches['cfrplugin_info'] = [
    'title' => t('Cfr plugin info'),
    /* @see _cfrplugin_info_cache_clear() */
    'callback' => '_cfrplugin_info_cache_clear',
  ];

  return $caches;
}

/**
 * Callback for admin_menu cache clearing.
 */
function _cfrplugin_info_cache_clear() {

  $implementations = &drupal_static('module_implements');
  if (isset($implementations['cfrplugin_info'])) {
    // Reset the cache for module_implements('cfrplugin_info'), but not for
    // other hooks.
    unset($implementations['cfrplugin_info']);
    module_implements('cfrplugin_info');
    module_implements_write_cache();
  }

  cache_clear_all('cfrplugin:', 'cache', TRUE);
}
